name: Deploy to GitHub Packages

on: [ workflow_dispatch ]

jobs:
  build:
    env:
      ORG_GRADLE_PROJECT_githubUsername: ${{ secrets.PAT_USER }}
      ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.PAT_PACKAGES_AND_REPO }}

    runs-on: ubuntu-latest

    steps:
      - name: Check out latest code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.3.0
        with:
          java-version: 1.8

      - name: Publish to GitHub Packages
        run: ./gradlew publish
